package event

import ()

const (
	HTTP_REQUEST_EVENT_TYPE                = 1000
	HTTP_RESPONSE_EVENT_TYPE               = 1001
	HTTP_CHUNK_EVENT_TYPE                  = 1002
	HTTP_ERROR_EVENT_TYPE                  = 1003
	HTTP_CONNECTION_EVENT_TYPE             = 1004
	RESERVED_SEGMENT_EVENT_TYPE            = 48100
	COMPRESS_EVENT_TYPE                    = 1500
	ENCRYPT_EVENT_TYPE                     = 1501
	AUTH_REQUEST_EVENT_TYPE                = 2000
	AUTH_RESPONSE_EVENT_TYPE               = 2001
	USER_OPERATION_EVENT_TYPE              = 2010
	GROUP_OPERATION_EVENT_TYPE             = 2011
	USER_LIST_REQUEST_EVENT_TYPE           = 2012
	GROUOP_LIST_REQUEST_EVENT_TYPE         = 2013
	USER_LIST_RESPONSE_EVENT_TYPE          = 2014
	GROUOP_LIST_RESPONSE_EVENT_TYPE        = 2015
	BLACKLIST_OPERATION_EVENT_TYPE         = 2016
	ADMIN_RESPONSE_EVENT_TYPE              = 2020
	SERVER_CONFIG_EVENT_TYPE               = 2050
	REQUEST_SHARED_APPID_EVENT_TYPE        = 2017
	REQUEST_SHARED_APPID_RESULT_EVENT_TYPE = 2018
	SHARE_APPID_EVENT_TYPE                 = 2019
	REQUEST_ALL_SHARED_APPID_EVENT_TYPE    = 2021
	//	EVENT_TRANSACTION_COMPLETE_TYPE        = 11505
	//
	//	EVENT_SEQUNCEIAL_CHUNK_TYPE            = 11504
	//	EVENT_SOCKET_CONNECT_RES_TYPE          = 11503
	//	EVENT_SOCKET_CONNECT_REQ_TYPE          = 11502
	//	EVENT_REST_NOTIFY_TYPE                 = 11501
	//	EVENT_REST_REQEUST_TYPE                = 11500
	EVENT_RSOCKET_ACCEPTED_TYPE         = 11506
	EVENT_TCP_CONNECTION_TYPE           = 12000
	EVENT_TCP_CHUNK_TYPE                = 12001
	EVENT_USER_LOGIN_TYPE               = 12002
	EVENT_SOCKET_READ_TYPE              = 13000
	EVENT_SOCKET_CONNECT_WITH_DATA_TYPE = 13001

	COMPRESSOR_NONE    uint32 = 0
	COMPRESSOR_SNAPPY  uint32 = 1
	COMPRESSOR_LZF     uint32 = 2
	COMPRESSOR_FASTLZ  uint32 = 3
	COMPRESSOR_QUICKLZ uint32 = 4
	COMPRESSOR_LZ4     uint32 = 5

	ENCRYPTER_NONE uint32 = 0
	ENCRYPTER_SE1  uint32 = 1
	ENCRYPTER_RC4  uint32 = 2

	HTTP_CONN_OPENED uint64 = 1
	HTTP_CONN_CLOSED uint64 = 2

	TCP_CONN_OPENED uint32 = 1
	TCP_CONN_CLOSED uint32 = 2

	APPID_SHARE   uint32 = 0
	APPID_UNSHARE uint32 = 1
)
